// export enum CoreEnum {
//     PhoenixFeather = "Phoenix Feather",
//     snallygasterHeartstring = "Snallygaster Heartstring",
//     test = "test"
// }

// export enum WoodEnum {
//     Cypress = "Cypress",
//     Spruce = "Spruce",
//     Holly = "Holly"
// }

export const woods: string[] = ['Acacia',
    'Alder',
    'Apple',
    'Ash',
    'Aspen',
    'Beech',
    'Blackthorn',
    'Black Walnut',
    'Cedar',
    'Cherry',
    'Chestnut',
    'Cypress',
    'Dogwood',
    'Ebony',
    'English oak',
    'Elder',
    'Elm',
    'Fir',
    'Hawthorn',
    'Hazel',
    'Holly',
    'Hornbeam',
    'Larch',
    'Laurel',
    'Maple',
    'Pear',
    'Pine',
    'Poplar',
    'Red oak',
    'Redwood',
    'Reed',
    'Rosewood',
    'Rowan',
    'Silver lime',
    'Spruce',
    'Snakewood',
    'Sugar Maple',
    'Sycamore',
    'Tamarack',
    'Vine',
    'Walnut',
    'Willow',
    'Yew'
];

export const cores: string[] = ['Unicorn hair',
    'Dragon heartstring',
    'Phoenix feather',
    'Veela hair',
    'Thestral tail hair',
    'Troll whisker',
    'Kelpie hair',
    'Thunderbird tail feather',
    'Wampus cat hair',
    'White River Monster spine',
    'Rougarou hair',
    'Kneazle whiskers',
    'Horned Serpent horn',
    'Snallygaster heartstring',
    'Jackalope antler',
    'Basilisk horn'
];

export const makers: string[] = [
    'Cosme Acajor',
    'Violetta Beauvais',
    'Arturo Cephalopos',
    'Death',
    'Mykew Gregorovitch',
    'Johannes Jonker',
    'Jimmy Kiddell',
    'Antioch Peverell',
    'Geraint Ollivander',
    'Gerbold Ollivander',
    'Gervaise Ollivander',
    'Garrick Ollivander',
    'Thiago Quintana',
    'Shikoba Wolfe',
    'Isolt Sayre',
    'James Steward',
    'Salazar Slytherin',
]


export const flexibilities = [
    "Very flexible",
    "Quite flexible",
    "Surprisingly swishy",
    "Swishy",
    "Quite bendy",
    "Fairly bendy",
    "Whippy",
    "Pliant",
    "Supple",
    "Reasonably supple",
    "Slightly springy",
    "Slightly yielding",
    "Solid",
    "Stiff",
    "Hard",
    "Rigid",
    "Unbending",
    "Unyielding",
    "Brittle",
]